# Generated by Django 6.0.3 on 2026-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cod', 'Cash on Delivery'), ('failed', 'Failed')], default='unpaid', max_length=10),
        ),
    ]
